#!/bin/bash

setup_dir=$(pwd)/.vscode/setup

case $1 in
    -h|--help)
        echo "Usage: setup-devcontainer [OPTION]"
        echo "Copy UDev rules or install additional features"
        echo ""
        echo "With no OPTION specified, the script will copy the UDev .rules files to $setup_dir."
        echo ""
        echo "  -U, --install-udev    Copies UDev rule files (default action)"
        echo "  -h, --help            Displays this help"
        ;;

    -U|--install-udev|"")
        mkdir -p $setup_dir
        cp /usr/share/openocd/contrib/60-openocd.rules $setup_dir/
        cp /opt/devcontainer/install-rules $setup_dir/
        ;;

    *)
        echo "setup-devcontainer: invalid option -- '$1'"
        echo "Try 'setup-devcontainer --help' for more information"
        ;;
esac
